/**
 * Registry of all 37+ supported embedding models.
 * Models are grouped by provider; the UI uses this list to populate the picker.
 */
import type { EmbeddingModel, EmbeddingProviderType } from "./types";

// ── OpenAI ────────────────────────────────────────────────────────────────────
const OPENAI: EmbeddingModel[] = [
  {
    id: "text-embedding-3-small",
    displayName: "text-embedding-3-small",
    provider: "openai",
    dimensions: 1536,
    contextLength: 8191,
    requiresApiKey: true,
    isLocal: false,
    matryoshka: true,
    supportsTaskType: false,
    bestFor: "quality",
    note: "Best price/quality ratio",
  },
  {
    id: "text-embedding-3-large",
    displayName: "text-embedding-3-large",
    provider: "openai",
    dimensions: 3072,
    contextLength: 8191,
    requiresApiKey: true,
    isLocal: false,
    matryoshka: true,
    supportsTaskType: false,
    bestFor: "quality",
    note: "Highest quality OpenAI model",
  },
  {
    id: "text-embedding-ada-002",
    displayName: "text-embedding-ada-002",
    provider: "openai",
    dimensions: 1536,
    contextLength: 8191,
    requiresApiKey: true,
    isLocal: false,
    matryoshka: false,
    supportsTaskType: false,
    note: "Legacy — cheapest OpenAI",
  },
];

// ── Voyage AI ─────────────────────────────────────────────────────────────────
const VOYAGE: EmbeddingModel[] = [
  {
    id: "voyage-code-3",
    displayName: "voyage-code-3",
    provider: "voyage",
    dimensions: 1024,
    contextLength: 32000,
    requiresApiKey: true,
    isLocal: false,
    matryoshka: true,
    supportsTaskType: false,
    bestFor: "code",
    note: "13.8% better than OpenAI on code retrieval ★",
  },
  {
    id: "voyage-3-large",
    displayName: "voyage-3-large",
    provider: "voyage",
    dimensions: 1024,
    contextLength: 32000,
    requiresApiKey: true,
    isLocal: false,
    matryoshka: true,
    supportsTaskType: false,
    bestFor: "quality",
    note: "Best general + multilingual",
  },
  {
    id: "voyage-3.5",
    displayName: "voyage-3.5",
    provider: "voyage",
    dimensions: 1024,
    contextLength: 32000,
    requiresApiKey: true,
    isLocal: false,
    matryoshka: true,
    supportsTaskType: false,
    note: "Optimized general-purpose",
  },
  {
    id: "voyage-3.5-lite",
    displayName: "voyage-3.5-lite",
    provider: "voyage",
    dimensions: 1024,
    contextLength: 32000,
    requiresApiKey: true,
    isLocal: false,
    matryoshka: true,
    supportsTaskType: false,
    bestFor: "speed",
    note: "Latency/cost optimized",
  },
];

// ── Jina AI ───────────────────────────────────────────────────────────────────
const JINA: EmbeddingModel[] = [
  {
    id: "jina-embeddings-v3",
    displayName: "jina-embeddings-v3",
    provider: "jina",
    dimensions: 1024,
    contextLength: 8192,
    requiresApiKey: true,
    isLocal: false,
    matryoshka: true,
    supportsTaskType: true,
    bestFor: "multilingual",
    note: "Task-specific LoRA, 89 languages",
  },
  {
    id: "jina-embeddings-v5-text-small",
    displayName: "jina-embeddings-v5-text-small",
    provider: "jina",
    dimensions: 1024,
    contextLength: 32768,
    requiresApiKey: true,
    isLocal: false,
    matryoshka: true,
    supportsTaskType: true,
    note: "5th gen, 32K context",
  },
  {
    id: "jina-embeddings-v5-text-nano",
    displayName: "jina-embeddings-v5-text-nano",
    provider: "jina",
    dimensions: 768,
    contextLength: 8192,
    requiresApiKey: true,
    isLocal: false,
    matryoshka: true,
    supportsTaskType: true,
    bestFor: "speed",
    note: "Fastest Jina model",
  },
];

// ── Mistral ───────────────────────────────────────────────────────────────────
const MISTRAL: EmbeddingModel[] = [
  {
    id: "mistral-embed",
    displayName: "mistral-embed",
    provider: "mistral",
    dimensions: 1024,
    contextLength: 8192,
    requiresApiKey: true,
    isLocal: false,
    matryoshka: false,
    supportsTaskType: false,
    note: "Fast, balanced quality",
  },
];

// ── OpenRouter ────────────────────────────────────────────────────────────────
const OPENROUTER: EmbeddingModel[] = [
  {
    id: "openai/text-embedding-3-small",
    displayName: "openai/text-embedding-3-small",
    provider: "openrouter",
    dimensions: 1536,
    contextLength: 8191,
    requiresApiKey: true,
    isLocal: false,
    matryoshka: true,
    supportsTaskType: false,
    note: "OpenAI via OpenRouter",
  },
  {
    id: "openai/text-embedding-3-large",
    displayName: "openai/text-embedding-3-large",
    provider: "openrouter",
    dimensions: 3072,
    contextLength: 8191,
    requiresApiKey: true,
    isLocal: false,
    matryoshka: true,
    supportsTaskType: false,
    note: "OpenAI large via OpenRouter",
  },
  {
    id: "google/gemini-embedding-2-preview",
    displayName: "google/gemini-embedding-2-preview",
    provider: "openrouter",
    dimensions: 3072,
    contextLength: 8192,
    requiresApiKey: true,
    isLocal: false,
    matryoshka: true,
    supportsTaskType: false,
    note: "Multimodal text+image",
  },
  {
    id: "perplexity/pplx-embed-v1-4b",
    displayName: "perplexity/pplx-embed-v1-4b",
    provider: "openrouter",
    dimensions: 1024,
    contextLength: 8192,
    requiresApiKey: true,
    isLocal: false,
    matryoshka: false,
    supportsTaskType: false,
    bestFor: "quality",
    note: "Web-scale retrieval, 4B params",
  },
  {
    id: "perplexity/pplx-embed-v1-0.6b",
    displayName: "perplexity/pplx-embed-v1-0.6b",
    provider: "openrouter",
    dimensions: 1024,
    contextLength: 8192,
    requiresApiKey: true,
    isLocal: false,
    matryoshka: false,
    supportsTaskType: false,
    bestFor: "speed",
    note: "Lightweight, low-latency",
  },
  {
    id: "nvidia/llama-nemotron-embed-vl-1b-v2",
    displayName: "nvidia/llama-nemotron-embed-vl-1b-v2",
    provider: "openrouter",
    dimensions: 4096,
    contextLength: 4096,
    requiresApiKey: true,
    isLocal: false,
    matryoshka: false,
    supportsTaskType: false,
    bestFor: "free",
    note: "Free tier, multimodal",
  },
  {
    id: "qwen/qwen3-embedding-0.6b",
    displayName: "qwen/qwen3-embedding-0.6b",
    provider: "openrouter",
    dimensions: 1024,
    contextLength: 8192,
    requiresApiKey: true,
    isLocal: false,
    matryoshka: false,
    supportsTaskType: false,
    bestFor: "speed",
    note: "Fast, code-aware",
  },
  {
    id: "thenlper/gte-large",
    displayName: "thenlper/gte-large",
    provider: "openrouter",
    dimensions: 1024,
    contextLength: 512,
    requiresApiKey: true,
    isLocal: false,
    matryoshka: false,
    supportsTaskType: false,
    note: "Strong retrieval quality",
  },
  {
    id: "intfloat/multilingual-e5-large",
    displayName: "intfloat/multilingual-e5-large",
    provider: "openrouter",
    dimensions: 1024,
    contextLength: 512,
    requiresApiKey: true,
    isLocal: false,
    matryoshka: false,
    supportsTaskType: false,
    bestFor: "multilingual",
    note: "90+ languages",
  },
  {
    id: "sentence-transformers/all-minilm-l12-v2",
    displayName: "sentence-transformers/all-minilm-l12-v2",
    provider: "openrouter",
    dimensions: 384,
    contextLength: 512,
    requiresApiKey: true,
    isLocal: false,
    matryoshka: false,
    supportsTaskType: false,
    bestFor: "speed",
    note: "Ultra-fast, tiny footprint",
  },
];

// ── Cohere ────────────────────────────────────────────────────────────────────
const COHERE: EmbeddingModel[] = [
  {
    id: "embed-v4.0",
    displayName: "embed-v4.0",
    provider: "cohere",
    dimensions: 1536,
    contextLength: 128000,
    requiresApiKey: true,
    isLocal: false,
    matryoshka: true,
    supportsTaskType: true,
    note: "128K context — embed whole files",
  },
  {
    id: "embed-english-v3.0",
    displayName: "embed-english-v3.0",
    provider: "cohere",
    dimensions: 1024,
    contextLength: 512,
    requiresApiKey: true,
    isLocal: false,
    matryoshka: false,
    supportsTaskType: true,
    note: "English — high quality",
  },
  {
    id: "embed-english-light-v3.0",
    displayName: "embed-english-light-v3.0",
    provider: "cohere",
    dimensions: 384,
    contextLength: 512,
    requiresApiKey: true,
    isLocal: false,
    matryoshka: false,
    supportsTaskType: true,
    bestFor: "speed",
    note: "English — fast + cheap",
  },
  {
    id: "embed-multilingual-v3.0",
    displayName: "embed-multilingual-v3.0",
    provider: "cohere",
    dimensions: 1024,
    contextLength: 512,
    requiresApiKey: true,
    isLocal: false,
    matryoshka: false,
    supportsTaskType: true,
    bestFor: "multilingual",
    note: "100+ languages",
  },
  {
    id: "embed-multilingual-light-v3.0",
    displayName: "embed-multilingual-light-v3.0",
    provider: "cohere",
    dimensions: 384,
    contextLength: 512,
    requiresApiKey: true,
    isLocal: false,
    matryoshka: false,
    supportsTaskType: true,
    bestFor: "multilingual",
    note: "Multilingual — fast",
  },
];

// ── Ollama ────────────────────────────────────────────────────────────────────
const OLLAMA: EmbeddingModel[] = [
  {
    id: "nomic-embed-text",
    displayName: "nomic-embed-text",
    provider: "ollama",
    dimensions: 768,
    contextLength: 8192,
    requiresApiKey: false,
    isLocal: true,
    matryoshka: false,
    supportsTaskType: false,
    note: "Default — zero config, no API key",
  },
  {
    id: "all-minilm",
    displayName: "all-minilm",
    provider: "ollama",
    dimensions: 384,
    contextLength: 512,
    requiresApiKey: false,
    isLocal: true,
    matryoshka: false,
    supportsTaskType: false,
    bestFor: "speed",
    note: "Ultra-fast, smallest",
  },
  {
    id: "mxbai-embed-large",
    displayName: "mxbai-embed-large",
    provider: "ollama",
    dimensions: 1024,
    contextLength: 512,
    requiresApiKey: false,
    isLocal: true,
    matryoshka: false,
    supportsTaskType: false,
    note: "Good general quality",
  },
  {
    id: "snowflake-arctic-embed",
    displayName: "snowflake-arctic-embed",
    provider: "ollama",
    dimensions: 1024,
    contextLength: 512,
    requiresApiKey: false,
    isLocal: true,
    matryoshka: false,
    supportsTaskType: false,
    note: "Strong retrieval",
  },
  {
    id: "snowflake-arctic-embed2",
    displayName: "snowflake-arctic-embed2",
    provider: "ollama",
    dimensions: 1024,
    contextLength: 8192,
    requiresApiKey: false,
    isLocal: true,
    matryoshka: false,
    supportsTaskType: false,
    note: "Latest Snowflake, longer context",
  },
  {
    id: "bge-large",
    displayName: "bge-large",
    provider: "ollama",
    dimensions: 1024,
    contextLength: 512,
    requiresApiKey: false,
    isLocal: true,
    matryoshka: false,
    supportsTaskType: false,
    bestFor: "quality",
    note: "Strong English retrieval",
  },
  {
    id: "bge-m3",
    displayName: "bge-m3",
    provider: "ollama",
    dimensions: 1024,
    contextLength: 8192,
    requiresApiKey: false,
    isLocal: true,
    matryoshka: false,
    supportsTaskType: false,
    bestFor: "multilingual",
    note: "Multilingual + multi-function",
  },
  {
    id: "e5-large",
    displayName: "e5-large",
    provider: "ollama",
    dimensions: 1024,
    contextLength: 512,
    requiresApiKey: false,
    isLocal: true,
    matryoshka: false,
    supportsTaskType: false,
    note: "Instruction-following",
  },
  {
    id: "jina-embeddings-v2-base-en",
    displayName: "jina-embeddings-v2-base-en",
    provider: "ollama",
    dimensions: 768,
    contextLength: 8192,
    requiresApiKey: false,
    isLocal: true,
    matryoshka: false,
    supportsTaskType: false,
    note: "8K context window",
  },
  {
    id: "paraphrase-multilingual",
    displayName: "paraphrase-multilingual",
    provider: "ollama",
    dimensions: 768,
    contextLength: 512,
    requiresApiKey: false,
    isLocal: true,
    matryoshka: false,
    supportsTaskType: false,
    bestFor: "multilingual",
    note: "50+ languages",
  },
  {
    id: "granite-embedding",
    displayName: "granite-embedding",
    provider: "ollama",
    dimensions: 768,
    contextLength: 512,
    requiresApiKey: false,
    isLocal: true,
    matryoshka: false,
    supportsTaskType: false,
    note: "IBM Granite family",
  },
];

// ── n9router ──────────────────────────────────────────────────────────────────
// Routes through your local n9router instance; uses its URL + API key from
// the n9router settings section.  Model IDs match n9router's /v1/models/embedding.
const N9ROUTER: EmbeddingModel[] = [
  {
    id: "n9router/openai/text-embedding-3-small",
    displayName: "openai/text-embedding-3-small",
    provider: "n9router",
    dimensions: 1536,
    contextLength: 8191,
    requiresApiKey: false, // key comes from n9router config
    isLocal: false,
    matryoshka: true,
    supportsTaskType: false,
    bestFor: "quality",
    note: "Best price/quality — via n9router",
  },
  {
    id: "n9router/openai/text-embedding-3-large",
    displayName: "openai/text-embedding-3-large",
    provider: "n9router",
    dimensions: 3072,
    contextLength: 8191,
    requiresApiKey: false,
    isLocal: false,
    matryoshka: true,
    supportsTaskType: false,
    bestFor: "quality",
    note: "Highest quality OpenAI — via n9router",
  },
  {
    id: "n9router/gemini/text-embedding-004",
    displayName: "gemini/text-embedding-004",
    provider: "n9router",
    dimensions: 768,
    contextLength: 2048,
    requiresApiKey: false,
    isLocal: false,
    matryoshka: false,
    supportsTaskType: false,
    note: "Google Gemini — via n9router",
  },
  {
    id: "n9router/voyage-ai/voyage-code-3",
    displayName: "voyage-ai/voyage-code-3",
    provider: "n9router",
    dimensions: 1024,
    contextLength: 32000,
    requiresApiKey: false,
    isLocal: false,
    matryoshka: true,
    supportsTaskType: false,
    bestFor: "code",
    note: "Best for code retrieval ★ — via n9router",
  },
  {
    id: "n9router/mistral/mistral-embed",
    displayName: "mistral/mistral-embed",
    provider: "n9router",
    dimensions: 1024,
    contextLength: 8192,
    requiresApiKey: false,
    isLocal: false,
    matryoshka: false,
    supportsTaskType: false,
    bestFor: "speed",
    note: "Fast + balanced — via n9router",
  },
  {
    id: "n9router/nvidia/llama-nemotron-embed-vl-1b-v2",
    displayName: "nvidia/llama-nemotron-embed-vl-1b-v2",
    provider: "n9router",
    dimensions: 4096,
    contextLength: 4096,
    requiresApiKey: false,
    isLocal: false,
    matryoshka: false,
    supportsTaskType: false,
    bestFor: "free",
    note: "Free tier — via n9router",
  },
];

// ── LM Studio ─────────────────────────────────────────────────────────────────
const LMSTUDIO: EmbeddingModel[] = [
  {
    id: "lmstudio-loaded",
    displayName: "(any loaded model)",
    provider: "lmstudio",
    dimensions: 0, // user-defined
    contextLength: 0, // model-dependent
    requiresApiKey: false,
    isLocal: true,
    matryoshka: false,
    supportsTaskType: false,
    note: "Uses whatever model is loaded in LM Studio",
  },
];

// ── Full registry ─────────────────────────────────────────────────────────────

export const ALL_MODELS: EmbeddingModel[] = [
  ...OLLAMA,
  ...OPENAI,
  ...VOYAGE,
  ...JINA,
  ...MISTRAL,
  ...OPENROUTER,
  ...COHERE,
  ...LMSTUDIO,
  ...N9ROUTER,
];

/** Models grouped by provider for the settings picker. */
export const MODELS_BY_PROVIDER: Record<
  EmbeddingProviderType,
  EmbeddingModel[]
> = {
  ollama: OLLAMA,
  openai: OPENAI,
  voyage: VOYAGE,
  jina: JINA,
  mistral: MISTRAL,
  openrouter: OPENROUTER,
  cohere: COHERE,
  lmstudio: LMSTUDIO,
  n9router: N9ROUTER,
};

export const PROVIDER_DISPLAY: Record<
  EmbeddingProviderType,
  { label: string; note: string }
> = {
  ollama: { label: "Ollama (local)", note: "no key needed" },
  openai: { label: "OpenAI", note: "API key required" },
  voyage: { label: "Voyage AI", note: "best for code ★" },
  jina: { label: "Jina AI", note: "task-specific LoRA" },
  mistral: { label: "Mistral", note: "fast + balanced" },
  openrouter: { label: "OpenRouter", note: "1 key → 25+ models" },
  cohere: { label: "Cohere", note: "128K context" },
  lmstudio: { label: "LM Studio (local)", note: "custom endpoint" },
  n9router: { label: "n9router", note: "uses n9router config" },
};

export function findModel(id: string): EmbeddingModel | undefined {
  return ALL_MODELS.find((m) => m.id === id);
}

export function modelsForProvider(
  provider: EmbeddingProviderType,
): EmbeddingModel[] {
  return MODELS_BY_PROVIDER[provider] ?? [];
}
